export { SOURCES, FACTS, PREDEFINED_ENTITIES, SKIP_FOLDERS, RESULT_ELEMENTS, isXmlName, source, factPage } from './data.js';
export { grouped, parseSize, sizeText, listText, plural } from './size.js';
export { safeText, flat } from './text.js';
export { SCALE, scaledPercent, atLeast, atMost, percentText, thresholdText } from './ratio.js';
export { FILE_LIMITS, fileError, readBounded, displayPath, isBinary, decodeText, readTextFile, readRunPaths, evidenceState } from './files.js';
export { XML_LIMITS, XmlError, lineStarts, positionOf, decodeReferences, parseXml, xmlProblem } from './xml.js';
export { JSON_LIMITS, JsonError, parseJson, jsonProblem } from './json.js';
export { CSV_LIMITS, CsvError, isDelimiter, parseCsv } from './csv.js';
export { GLOB_LIMITS, globProblem, matchGlob, matchesAny } from './glob.js';
export { RESULT_KINDS, testKey, testLabel, readJunit, summarizeRun } from './junit.js';
export { LCOV_LIMITS, LcovError, parseLcov } from './lcov.js';
export { CoberturaError, readCobertura } from './cobertura.js';
export { MAX_PATH_LENGTH, normalizePath, createStore, addFile, fileSums, sumStore, matchChanged } from './coverage.js';
export { DEFAULT_COLUMNS, norm, readDefects } from './defects.js';
export { CRITERIA_LIMITS, KEYS, CriteriaError, evidencePath, validateCriteria, readCriteria } from './criteria.js';
export { STATUSES, MAX_DETAILS, MAX_FACTS, GATES, AREAS, evaluate, decide } from './gates.js';
export { LIMITS, InputError, checkPaths } from './check.js';
export { toText, toMarkdown, toJson, mdCell } from './report.js';
export { parseArgs, main, USAGE, VERSION } from './cli.js';
